version: '3'
services:
  api:
    build: ./api/
    container_name: api
    ports:
      - 8081:8081
    volumes:
      - ./api/app/:/app/
    env_file:
      - ./api/.env

  postgres:
    image: postgres:13.1
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api
    volumes:
      - ./init_sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
